/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SegundaJanela.java
 *
 * Created on 29/09/2011, 21:00:59
 */

package padt7.aula1;

import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class SegundaJanela extends javax.swing.JFrame {

    /** Creates new form SegundaJanela */
    public SegundaJanela() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minha segunda janela");

        jButton1.setText("Clique aqui!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(103, 103, 103)
                .add(jButton1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(70, 70, 70)
                .add(jButton1)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       String resposta = JOptionPane.showInputDialog(this, "Qual a sua idade?");

       try {
           int idade = Integer.parseInt(resposta);

           int opcao = JOptionPane.showConfirmDialog(this,
                   "Você realmente possui essa idade?",
                   "Confirmação",
                   JOptionPane.YES_NO_OPTION);

           if (opcao == JOptionPane.YES_OPTION) {

               if (idade >= 18) {
                   JOptionPane.showMessageDialog(this, "Você é maior de idade");
               } else {
                   JOptionPane.showMessageDialog(this, "Você não é maior de idade");
               }

           } else {
                jButton1ActionPerformed(evt);
           }
       } catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(this, "É obrigatório informar a idade!");
           jButton1ActionPerformed(evt);
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundaJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
