/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArvoreDiretorios.java
 *
 * Created on 01/10/2011, 12:26:35
 */

package padt7.aula3;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author david
 */
public class ArvoreDiretorios extends javax.swing.JFrame {

    /** Creates new form ArvoreDiretorios */
    public ArvoreDiretorios() {
        initComponents();

        File diretorio = new File("/Users/david/Documents/conference");
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Raiz");

        carregarSubDiretorios(diretorio, raiz);

        jTree1.setModel(new DefaultTreeModel(raiz));
    }

    private void carregarSubDiretorios(File arquivoRaiz, DefaultMutableTreeNode noRaiz) {
        DefaultMutableTreeNode noArquivo = new DefaultMutableTreeNode(arquivoRaiz.getName());
        noRaiz.add(noArquivo);

        if (arquivoRaiz.isDirectory()) {
            for (File arquivo : arquivoRaiz.listFiles()) {
                carregarSubDiretorios(arquivo, noArquivo);
            }
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        selecaoArquivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        selecaoArquivo.setText("Selecione um arquivo");
        selecaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecaoArquivoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(selecaoArquivo)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(137, 137, 137)
                .add(selecaoArquivo)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecaoArquivoActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION ) {
            File arquivoSelecionado = chooser.getSelectedFile();
            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Raiz");

            carregarSubDiretorios(arquivoSelecionado, raiz);

            jTree1.setModel(new DefaultTreeModel(raiz));
        }

    }//GEN-LAST:event_selecaoArquivoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArvoreDiretorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton selecaoArquivo;
    // End of variables declaration//GEN-END:variables

}
