/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExemploComboBox.java
 *
 * Created on 01/10/2011, 08:48:52
 */

package padt7.aula3;

import java.awt.Color;

/**
 *
 * @author david
 */
public class ExemploComboBox extends javax.swing.JFrame {

    /** Creates new form ExemploComboBox */
    public ExemploComboBox() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboCores = new javax.swing.JComboBox();
        painelCores = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboCores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preto", "Branco", "Azul", "Amarelo", "Verde", "Vermelho" }));
        comboCores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCoresActionPerformed(evt);
            }
        });

        painelCores.setBackground(new java.awt.Color(0, 0, 0));

        org.jdesktop.layout.GroupLayout painelCoresLayout = new org.jdesktop.layout.GroupLayout(painelCores);
        painelCores.setLayout(painelCoresLayout);
        painelCoresLayout.setHorizontalGroup(
            painelCoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        painelCoresLayout.setVerticalGroup(
            painelCoresLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(106, 106, 106)
                        .add(comboCores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(144, 144, 144)
                        .add(painelCores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(48, 48, 48)
                .add(comboCores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(painelCores, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCoresActionPerformed
        String item = (String) comboCores.getSelectedItem();

        if (item.equals("Preto")) {
            painelCores.setBackground(Color.BLACK);;
        } else if (item.equals("Branco")) {
            painelCores.setBackground(Color.WHITE);
        } else if (item.equals("Azul")) {
            painelCores.setBackground(Color.BLUE);
        } else if (item.equals("Amarelo")) {
            painelCores.setBackground(Color.YELLOW);
        } else if (item.equals("Verde")) {
            painelCores.setBackground(Color.GREEN);
        } else {
            painelCores.setBackground(Color.RED);
        }

    }//GEN-LAST:event_comboCoresActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboCores;
    private javax.swing.JPanel painelCores;
    // End of variables declaration//GEN-END:variables

}
